### ISSUE TITLE
Create UI Design

### ISSUE THREAD

**Issue by ruili4UCSD** [cse110-sp23-group26/BugCatchers#1]
UI design
Detail: https://canvas.ucsd.edu/courses/44983/assignments/617834, 
Include: 
- rough draft (already completed in first brainstorm activity)
- wireframe 
- highfidelity
Stored in /specs/interface/rough、/specs/interface/wireframes、/specs/interface/highfidelity,
Due this Sunday

**Comment by nick-ls** [comment]
This has been uploaded and completed
