### ISSUE TITLE
Fix the fortune card display button

### ISSUE THREAD

**Issue by nick-ls** [cse110-sp23-group26/BugCatchers#23]
## Issue
The display button does not open a menu showing past fortunes. Instead the fortunes are being added to the bottom of the document

## Proposed solution
Create a hidden element on the page that holds the fortune cards loaded from localstorage on the page loading. Whenever localstorage is updated, also update this hidden element. When the leaf icon is clicked, reveal the element, and when the element is clicked off of, then hide the element.

## Visual
![](https://cdn.discordapp.com/attachments/405158309725863946/1112495293578084512/image.png)

**Comment by QuanlingZhao** [comment]
Added fortune list that dynamic read from storage on click.
